### ISSUE TITLE
Create Login page with JWT

### ISSUE THREAD

**Issue by g-bolmida** [MiriConf/miriconf-frontend#12]
Create a login page that can fetch a JWT from the backend using the credentials submitted in the login form and store the JWT as a cookie.

https://github.com/MiriConf/miriconf-backend/issues/6#issuecomment-1293034807

**Comment by g-bolmida** [comment]
https://www.postman.com

**Comment by jordanwentland** [comment]
Login page created and JWT token storing in cookie
